### ISSUE TITLE
RarArchive php 7.3

### ISSUE THREAD

**Issue by Serokuz22** [liquetsoft/fias-component#5]
Для распаковки используется pecl php-rar но он плохо поддерживается и до сих пор его нет под пхп 7.3 а уже вышла версия 7.4, сделайте возможность распаковки через exec

**Comment by marvin255** [comment]
С rar расширением ничем не могу помочь. Распаковка через консольную команду добавлена в v3.3.0 (#6).

**Comment by marvin255** [comment]
Пример:
```php
$commandTemplate = new \Liquetsoft\Fias\Component\Process\TemplateProcess('unrar x {{source}} {{destination}}');
$unpacker = new \Liquetsoft\Fias\Component\Unpacker\ProcessUnpacker($commandTemplate);
$unpacker->unpack($fileInfoArchive, $fileinfoDestination);
```
